const PASSWORD="Tavuk", STORAGE_KEY="fatihKasap2StateV2", OLD_STORAGE_KEY="fatihKasap2StateV1";

const ARTICLES=[
["Hähnchenbrust","Tavuk göğsü"],["Hähnchen-Innenfilet","Tavuk iç göğüs"],["Hähnchenschenkel (Keule)","Tavuk but"],["Hähnchen-Unterschenkel (Drumsticks)","Tavuk baget"],["Hähnchenoberkeule","Tavuk but üstü"],["Hähnchenflügel","Tavuk kanat"],["Ganzes Hähnchen","Bütün tavuk"],["Hähnchenhack","Tavuk kıyma"],["Hähnchenleber","Tavuk ciğer"],["Hähnchenherzen","Tavuk yürek"],
["Putenbrust","Hindi göğüs"],["Putenschenkel","Hindi but"],["Putenhack","Hindi kıyma"],
["Rinderhack (normal)","Dana kıyma (normal)"],["Rinderhack (fettreich)","Dana kıyma (yağlı)"],["Rindfleisch gewürfelt (Gulasch)","Dana kuşbaşı"],["Rindersteak","Dana biftek"],["Rinderschulter","Dana kol"],["Rinderkeule","Dana but"],["Rindernacken","Dana gerdan"],["Rinderbeinscheibe","Dana incik"],["Rind Suppenfleisch","Dana çorbalık et"],["Hackfleisch für Burger","Hamburgerlik kıyma"],
["Lammhack","Kuzu kıyma"],["Lammkeule","Kuzu but"],["Lammschulter","Kuzu kol"],["Lammnacken","Kuzu gerdan"],["Lammkotelett","Kuzu pirzola"],["Lammfleisch gewürfelt","Kuzu kuşbaşı"],
["Adana-Kebab-Fleisch (gewürzt)","Adana kebap harcı"],["Urfa-Kebab-Fleisch (mild)","Urfa kebap harcı"],["Köfte-Fleisch (gewürzt)","Köftelik kıyma"],["Tavuk Şiş (mariniert)","Tavuk şiş"],["Kuzu Şiş (mariniert)","Kuzu şiş"],["Dana Şiş (mariniert)","Dana şiş"],["Hähnchenflügel mariniert","Marine tavuk kanat"],
["Dönerfleisch Rind (roh)","Dana dönerlik et"],["Dönerfleisch Hähnchen (roh)","Tavuk dönerlik et"],
["Sucuk (Rindswurst)","Sucuk"],["Pastirma","Pastırma"],["Räucherwurst gemischt","Karışık füme sosis"],["Merguez (Rind/Lamm)","Merguez"],["Türkische Salami","Türk salam"],["Geflügelwurst","Tavuk sosis"],["Rinder-Hotdog-Wurst","Dana sosis"],
["Rinderleber","Dana ciğer"],["Lammleber","Kuzu ciğer"],["Rinderherz","Dana yürek"],["Lammherz","Kuzu yürek"],["Rinderniere","Dana böbrek"],["Lammniere","Kuzu böbrek"],["Kutteln (geputzt)","İşkembe temiz"],["Kutteln (ungeputzt)","İşkembe çiğ"],["Lammhirn","Kuzu beyin"],["Rinderhirn","Dana beyin"],["Rinderzunge","Dana dil"],
["Knochen gemischt (Suppe)","Çorbalık kemik"],["Markknochen","İlikli kemik"],["Lammkopf","Kuzu kelle"],["Kopffleisch Rind","Dana kelle eti"],["Lammfüße","Kuzu paça"],["Rinderfüße","İnek paça"],
["Gemischtes Hack (Rind+Lamm)","Karışık kıyma"],["Fertige Köfte (roh)","Hazır köfte"],["Fleisch für Çiğköfte","Çiğköftelik et"],["Kokoreç (roh)","Çiğ kokoreç"],["Kokoreç (gewürzt, fertig)","Hazır kokoreç"]
];

const DEFAULT_CUSTOMERS=["depo hurth","depo kalk","depo bild","arkadasch","kapadokya","depo mg","depo achen","almer bergheim","genus 1","erenel","aysu","erciyes","depo krefeld","harbi","fatih","depo duisburg","depo hamm","depo dortmund","depo herne","depo gelsenkirchen","depo hagen","depo wuppertal","sude","turpa","kairo","dost","basha"];

const T={
de:{exportTitle:"Export",company:"Firma",file:"Dateiname",excel:"Excel exportieren",pdf:"Einzel-PDFs exportieren",exportHint:"Exportiert nur Besteller mit tatsächlicher Bestellung. Leere Sayfa-Seiten werden übersprungen. Tavuk- und Tosun-Liste werden zusätzlich erstellt.",manage:"Kunden verwalten",customerName:"Kundenname",password:"Passwort",add:"Kunde hinzufügen",del:"Ausgewählten Kunden löschen",assign:"Sayfa-Zuordnung",assignHint:"Nur Besteller mit eingetragener Ware brauchen eine Sayfa. Bereich antippen zum Ein-/Ausklappen.",select:"Besteller auswählen",items:"Artikel",ware:"Ware",count:"Anzahl",search:"Artikel suchen…",none:"Kein Kunde",first:"Bitte zuerst Besteller auswählen.",wrong:"Falsches Passwort",enter:"Kundenname eingeben",confirm:"Kunden wirklich löschen?",unassignedActive:"aktive Besteller noch ohne Sayfa",assignedActive:"Alle Besteller mit Bestellung sind einer Sayfa zugeordnet.",mustAssignActive:"Vor dem Export brauchen nur Besteller mit Bestellung eine Sayfa-Zuordnung.",noActiveOrders:"Noch keine Bestellungen eingetragen.",lib:"Export-Bibliothek nicht geladen. Internetverbindung prüfen.",working:"PDFs werden erstellt…",done:"Export fertig.",noOrders:"Keine Eingabe",customer:"Besteller",date:"Datum",total:"TOPLAM",tavuk:"Tavuk Listesi",tosun:"Tosun Listesi",product:"Artikel",summary:"Gesamt",page:"Sayfa"},
tr:{exportTitle:"Dışa aktar",company:"Firma",file:"Dosya adı",excel:"Excel indir",pdf:"Ayrı PDF'leri indir",exportHint:"Yalnızca gerçek siparişi olan müşteriler dışa aktarılır. Boş Sayfa'lar atlanır. Tavuk ve Tosun listeleri ayrıca oluşturulur.",manage:"Müşterileri yönet",customerName:"Müşteri adı",password:"Şifre",add:"Müşteri ekle",del:"Seçili müşteriyi sil",assign:"Sayfa ataması",assignHint:"Yalnızca ürün girilmiş müşterilere Sayfa gerekir. Bölümü açmak/kapatmak için başlığa dokunun.",select:"Müşteri seç",items:"Ürünler",ware:"Ürün",count:"Adet",search:"Ürün ara…",none:"Müşteri yok",first:"Önce müşteri seçin.",wrong:"Şifre yanlış",enter:"Müşteri adı girin",confirm:"Müşteri silinsin mi?",unassignedActive:"siparişli müşteri henüz Sayfa'ya atanmadı",assignedActive:"Siparişi olan tüm müşteriler bir Sayfa'ya atandı.",mustAssignActive:"Dışa aktarmadan önce yalnızca siparişi olan müşterilere Sayfa atayın.",noActiveOrders:"Henüz sipariş girilmedi.",lib:"Dışa aktarma kütüphanesi yüklenmedi. İnterneti kontrol edin.",working:"PDF'ler hazırlanıyor…",done:"Dışa aktarma tamamlandı.",noOrders:"Giriş yok",customer:"Müşteri",date:"Tarih",total:"TOPLAM",tavuk:"Tavuk Listesi",tosun:"Tosun Listesi",product:"Ürün",summary:"Toplam",page:"Sayfa"}
};
