function styleCell(cell,style){if(cell)cell.s=style}
const S={title:{font:{bold:true,sz:14},alignment:{horizontal:'center'}},header:{font:{bold:true},fill:{fgColor:{rgb:'E7E7E7'}},alignment:{horizontal:'center',vertical:'center',wrapText:true},border:{top:{style:'thin',color:{rgb:'444444'}},bottom:{style:'thin',color:{rgb:'444444'}},left:{style:'thin',color:{rgb:'444444'}},right:{style:'thin',color:{rgb:'444444'}}}},customer:{font:{bold:true,underline:true,sz:12},alignment:{horizontal:'center',vertical:'center'},border:{top:{style:'thin',color:{rgb:'777777'}},bottom:{style:'thin',color:{rgb:'777777'}},left:{style:'thin',color:{rgb:'777777'}},right:{style:'thin',color:{rgb:'777777'}}}},normal:{border:{top:{style:'thin',color:{rgb:'BBBBBB'}},bottom:{style:'thin',color:{rgb:'BBBBBB'}},left:{style:'thin',color:{rgb:'BBBBBB'}},right:{style:'thin',color:{rgb:'BBBBBB'}}}},total:{font:{bold:true},fill:{fgColor:{rgb:'E7E7E7'}},border:{top:{style:'thin',color:{rgb:'444444'}},bottom:{style:'thin',color:{rgb:'444444'}},left:{style:'thin',color:{rgb:'444444'}},right:{style:'thin',color:{rgb:'444444'}}}}};

function makeSayfaSheet(p){
 const rows=[[companyName.value||company,'',''],[`Sayfa ${p}`,'',''],[t().date,today(),''],[]];const customerRows=[];
 activeCustomers().filter(c=>c.page===p).forEach(c=>{const cr=rows.length;rows.push([c.name,'','']);customerRows.push(cr);rows.push([t().ware,'kg',t().count]);currentOrders(c).forEach(r=>rows.push([r.name,Number(r.o.kg)||'',Number(r.o.count)||'']));rows.push([])});
 const ws=XLSX.utils.aoa_to_sheet(rows);ws['!cols']=[{wch:44},{wch:12},{wch:12}];ws['!merges']=[{s:{r:0,c:0},e:{r:0,c:2}},{s:{r:1,c:0},e:{r:1,c:2}},...customerRows.map(r=>({s:{r,c:0},e:{r,c:2}}))];styleCell(ws.A1,S.title);styleCell(ws.A2,S.title);customerRows.forEach(r=>{styleCell(ws[XLSX.utils.encode_cell({r,c:0})],S.customer);const hr=r+1;for(let c=0;c<3;c++)styleCell(ws[XLSX.utils.encode_cell({r:hr,c})],S.header)});const range=XLSX.utils.decode_range(ws['!ref']);for(let r=0;r<=range.e.r;r++){for(let c=0;c<=range.e.c;c++){const ref=XLSX.utils.encode_cell({r,c});if(ws[ref]&&!ws[ref].s&&r>3)styleCell(ws[ref],S.normal)}}ws['!pageSetup']={orientation:'portrait',fitToWidth:1,fitToHeight:1,paperSize:9};return ws;
}

function tavukIndices(){return ARTICLES.map((_,i)=>i).filter(i=>articleClass(i)==='tavuk')}
function tosunIndices(){return ARTICLES.map((_,i)=>i).filter(i=>articleClass(i)==='tosun')}
function cellSummary(o){if(!hasOrder(o))return '';const kg=Number(o.kg)>0?fmtNum(o.kg)+' kg':'';const ct=Number(o.count)>0?fmtNum(o.count):'';return kg&&ct?kg+' / '+ct:(kg||ct)}
function makeTavukSheet(){
 const inds=tavukIndices();const end=inds.length,c2=Math.max(1,Math.floor(end/3)+1),c3=Math.max(2,Math.floor(end*2/3)+1);const top=Array(inds.length+1).fill('');top[0]=companyName.value||company;top[c2]=t().tavuk;top[c3]=today();const rows=[top,[t().customer,...inds.map(i=>articleName(i))]];const sums=inds.map(()=>({kg:0,count:0}));activeCustomers().forEach(c=>{const vals=inds.map((i,k)=>{const o=orderAt(c.orders?.[i]);sums[k].kg+=Number(o.kg)||0;sums[k].count+=Number(o.count)||0;return cellSummary(o)});if(vals.some(Boolean))rows.push([c.name,...vals])});rows.push([t().total,...sums.map(cellSummary)]);const ws=XLSX.utils.aoa_to_sheet(rows);ws['!cols']=[{wch:24},...inds.map(()=>({wch:14}))];ws['!merges']=[{s:{r:0,c:0},e:{r:0,c:Math.max(0,Math.floor(end/3))}},{s:{r:0,c:c2},e:{r:0,c:Math.max(c2,Math.floor(end*2/3))}},{s:{r:0,c:c3},e:{r:0,c:end}}];for(let c=0;c<=end;c++)styleCell(ws[XLSX.utils.encode_cell({r:1,c})],S.header);const rr=XLSX.utils.decode_range(ws['!ref']).e.r;for(let c=0;c<=end;c++)styleCell(ws[XLSX.utils.encode_cell({r:rr,c})],S.total);styleCell(ws.A1,{font:{bold:true},alignment:{horizontal:'left'}});styleCell(ws[XLSX.utils.encode_cell({r:0,c:c2})],{font:{bold:true,sz:14},alignment:{horizontal:'center'}});styleCell(ws[XLSX.utils.encode_cell({r:0,c:c3})],{font:{bold:true},alignment:{horizontal:'right'}});ws['!pageSetup']={orientation:'landscape',fitToWidth:1,fitToHeight:1,paperSize:9};return ws;
}
function makeTosunSheet(){
 const inds=tosunIndices(),left=[];const totals=inds.map(i=>({i,kg:0,count:0}));activeCustomers().forEach(c=>{const parts=[];inds.forEach((i,k)=>{const o=orderAt(c.orders?.[i]);if(hasOrder(o)){parts.push(amountText(o)+' '+articleName(i));totals[k].kg+=Number(o.kg)||0;totals[k].count+=Number(o.count)||0}});if(parts.length)left.push([c.name,parts.join(' / ')])});const max=Math.max(left.length,totals.filter(x=>x.kg>0||x.count>0).length);const rows=[[companyName.value||company,'',t().tosun,today()],[t().customer,t().product,t().product,t().summary]];const activeTotals=totals.filter(x=>x.kg>0||x.count>0);for(let r=0;r<max;r++){const l=left[r]||['',''];const tr=activeTotals[r];rows.push([l[0],l[1],tr?articleName(tr.i):'',tr?cellSummary(tr):''])}const ws=XLSX.utils.aoa_to_sheet(rows);ws['!cols']=[{wch:22},{wch:70},{wch:35},{wch:18}];for(let c=0;c<4;c++)styleCell(ws[XLSX.utils.encode_cell({r:1,c})],S.header);const range=XLSX.utils.decode_range(ws['!ref']);for(let r=2;r<=range.e.r;r++)for(let c=0;c<4;c++)styleCell(ws[XLSX.utils.encode_cell({r,c})],S.normal);styleCell(ws.A1,{font:{bold:true}});styleCell(ws.C1,{font:{bold:true,sz:14},alignment:{horizontal:'center'}});ws['!pageSetup']={orientation:'landscape',fitToWidth:1,fitToHeight:1,paperSize:9};return ws;
}
function buildWorkbook(){const wb=XLSX.utils.book_new();usedPages().forEach(p=>XLSX.utils.book_append_sheet(wb,makeSayfaSheet(p),`Sayfa ${p}`));XLSX.utils.book_append_sheet(wb,makeTavukSheet(),'Tavuk Listesi');XLSX.utils.book_append_sheet(wb,makeTosunSheet(),'Tosun Listesi');return wb}
function exportExcel(){if(!validateAssignments())return;if(typeof XLSX==='undefined')return alert(t().lib);if(!activeCustomers().length)return alert(t().noActiveOrders);save();const wb=buildWorkbook();XLSX.writeFile(wb,cleanFileName(fileName.value)+'.xlsx');exportStatus.className='status ok';exportStatus.textContent=t().done}
