function sheetHTMLSayfa(p){const cs=customers.filter(c=>c.page===p);let h=`<div class="pdfsheet" style="width:1000px"><div class="topline"><div>${escapeHtml(companyName.value||company)}</div><div>Sayfa ${p}</div><div>${today()}</div></div>`;if(!cs.length)h+=`<p>${escapeHtml(t().noOrders)}</p>`;cs.forEach(c=>{h+=`<table style="margin-bottom:14px;width:100%"><tr><td class="customer-title" colspan="3">${escapeHtml(c.name)}</td></tr><tr><th>${escapeHtml(t().ware)}</th><th style="width:110px">kg</th><th style="width:110px">${escapeHtml(t().count)}</th></tr>`;const ord=currentOrders(c);if(!ord.length)h+=`<tr><td>${escapeHtml(t().noOrders)}</td><td></td><td></td></tr>`;else ord.forEach(r=>h+=`<tr><td>${escapeHtml(r.name)}</td><td>${escapeHtml(fmtNum(r.o.kg))}</td><td>${escapeHtml(fmtNum(r.o.count))}</td></tr>`);h+='</table>'});return h+'</div>'}
function sheetHTMLTavuk(){const inds=tavukIndices();const sums=inds.map(()=>({kg:0,count:0}));let h=`<div class="pdfsheet" style="width:1500px"><div class="topline"><div>${escapeHtml(companyName.value||company)}</div><div>${escapeHtml(t().tavuk)}</div><div>${today()}</div></div><table style="width:100%;table-layout:fixed"><tr><th style="width:150px">${escapeHtml(t().customer)}</th>`;inds.forEach(i=>h+=`<th style="font-size:10px;word-break:break-word">${escapeHtml(articleName(i))}</th>`);h+='</tr>';customers.forEach(c=>{const vals=inds.map((i,k)=>{const o=orderAt(c.orders?.[i]);sums[k].kg+=Number(o.kg)||0;sums[k].count+=Number(o.count)||0;return cellSummary(o)});if(vals.some(Boolean)){h+=`<tr><td style="font-weight:700">${escapeHtml(c.name)}</td>`;vals.forEach(v=>h+=`<td style="text-align:center;font-size:10px">${escapeHtml(v)}</td>`);h+='</tr>'}});h+=`<tr><td style="font-weight:700">${escapeHtml(t().total)}</td>`;sums.forEach(s=>h+=`<td style="font-weight:700;text-align:center;font-size:10px">${escapeHtml(cellSummary(s))}</td>`);return h+'</tr></table></div>'}
function sheetHTMLTosun(){const inds=tosunIndices(),left=[],totals=inds.map(i=>({i,kg:0,count:0}));customers.forEach(c=>{const parts=[];inds.forEach((i,k)=>{const o=orderAt(c.orders?.[i]);if(hasOrder(o)){parts.push(amountText(o)+' '+articleName(i));totals[k].kg+=Number(o.kg)||0;totals[k].count+=Number(o.count)||0}});if(parts.length)left.push([c.name,parts.join(' / ')])});let h=`<div class="pdfsheet" style="width:1300px"><div class="topline"><div>${escapeHtml(companyName.value||company)}</div><div>${escapeHtml(t().tosun)}</div><div>${today()}</div></div><div class="tosun-grid"><table><tr><th style="width:210px">${escapeHtml(t().customer)}</th><th>${escapeHtml(t().product)}</th></tr>`;left.forEach(r=>h+=`<tr><td style="font-weight:700">${escapeHtml(r[0])}</td><td>${escapeHtml(r[1])}</td></tr>`);h+='</table><table><tr><th>'+escapeHtml(t().product)+'</th><th style="width:130px">'+escapeHtml(t().summary)+'</th></tr>';totals.filter(x=>x.kg>0||x.count>0).forEach(x=>h+=`<tr><td>${escapeHtml(articleName(x.i))}</td><td>${escapeHtml(cellSummary(x))}</td></tr>`);return h+'</table></div></div>'}

async function htmlToOnePagePdf(html,name){const stage=document.getElementById('pdfStage');stage.innerHTML=html;const el=stage.firstElementChild;await new Promise(r=>setTimeout(r,25));const canvas=await html2canvas(el,{scale:1.35,backgroundColor:'#ffffff',useCORS:true,logging:false});const {jsPDF}=window.jspdf;const pdf=new jsPDF({orientation:'landscape',unit:'mm',format:'a4',compress:true});const pw=pdf.internal.pageSize.getWidth(),ph=pdf.internal.pageSize.getHeight(),m=4;const ratio=Math.min((pw-2*m)/canvas.width,(ph-2*m)/canvas.height);const w=canvas.width*ratio,h=canvas.height*ratio;pdf.addImage(canvas.toDataURL('image/jpeg',0.9),'JPEG',(pw-w)/2,(ph-h)/2,w,h,undefined,'FAST');stage.innerHTML='';return pdf.output('arraybuffer')}
async function exportAllPDFs(){
 if(!validateAssignments())return;if(typeof html2canvas==='undefined'||!window.jspdf||typeof JSZip==='undefined')return alert(t().lib);save();pdfBtn.disabled=true;excelBtn.disabled=true;exportStatus.className='status';exportStatus.textContent=t().working;
 try{const zip=new JSZip();for(let p=1;p<=10;p++){exportStatus.textContent=`${t().working} Sayfa ${p}/10`;zip.file(`Sayfa ${p}.pdf`,await htmlToOnePagePdf(sheetHTMLSayfa(p),`Sayfa ${p}`))}zip.file('Tavuk Listesi.pdf',await htmlToOnePagePdf(sheetHTMLTavuk(),'Tavuk Listesi'));zip.file('Tosun Listesi.pdf',await htmlToOnePagePdf(sheetHTMLTosun(),'Tosun Listesi'));const blob=await zip.generateAsync({type:'blob',compression:'DEFLATE'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=cleanFileName(fileName.value)+' PDFs.zip';document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1500);exportStatus.className='status ok';exportStatus.textContent=t().done}catch(e){console.error(e);exportStatus.className='status warn';exportStatus.textContent=String(e?.message||e)}finally{pdfBtn.disabled=false;excelBtn.disabled=false}
}

save();applyLanguage();
